<?php 

$LANG = array(
    "about" => "About us",
    "assignee" => "Assignee",
    "assigner" => "Assigner",
    "description" => "Description",
    "act" => "Action(s)",
    "tasktodo" => "Task name...",
    "addtask" => "Add new task",
    "task" => "Task",
    "daysopen" => "Day(s) open",
    "duedate" => "Due date",
    "priority" => "Priority",
    "action" => "Action",
    "edit" => "Edit",
    "delete" => "Delete",
    "high" => "High",
    "normal" => "Normal",
    "low" => "Low",
    "onhold" => "On hold",
    "tasks" => "To Do",
    "taskupdated" => "Task updated",
    "taskadded" => "Task added.",
    "trash" => "Deleted tasks",
    "progress" => "Tasks in progress",
    "backtohomepage" => "Back to the main page",
    "tobin" => "Trash Bin",
    "updatetask" => "Update task",
    "notasks" => "No tasks.",
    "todo" => "To Do",
    "daysleft" => " days left",
    "dayslate" => " days late",
    "today" => "Today!",
    "infotext" => 'infotext',
    "info" => "Info",
    "finishedtasks" => "Finished tasks",
);

?>